github.com/sirupsen/logrus             v1.9.4
golang.org/x/sys                       v0.43.0
github.com/golang-jwt/jwt/v5          v5.3.1
github.com/gorilla/mux                 v1.8.1
github.com/gorilla/websocket           v1.5.3
github.com/patrickmn/go-cache          v2.1.0
gopkg.in/check.v1                      4f90aeace3a26ad7021961c297b22c42160c7b25
