#!/bin/bash

is_numeric_version()
{
    [[ "$1" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+$ ]]
}

if [ -n "${VERSION_OVERRIDE:-}" ]; then
	if ! is_numeric_version "$VERSION_OVERRIDE"; then
		echo "VERSION_OVERRIDE must be a numeric semantic version" >&2
		exit 1
	fi
	VERSION=${VERSION_OVERRIDE#v}
else
	GIT_TAG=$(git tag --points-at HEAD | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' | LC_ALL=C sort | head -n 1 || true)

	if [[ -n "$GIT_TAG" ]]; then
		VERSION=${GIT_TAG#v}
	else
		VERSION="0.0.0"
	fi
fi
